/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SelectionRect } from "./utils/screen-selector";
export { SelectionRect } from "./utils/screen-selector";
export namespace Components {
    interface ImageEditor {
        "loadImage": (imageSrc: string | Blob) => Promise<void>;
    }
    interface ScreenshotEditor {
        /**
          * @default 'Take Screenshot'
         */
        "buttonLabel": string;
        /**
          * @default 'bottom-right'
         */
        "buttonPosition": string;
        "openEditor": (image: string | Blob) => Promise<void>;
        /**
          * @default true
         */
        "showButton": boolean;
        "startScreenshot": () => Promise<void>;
    }
}
export interface ImageEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLImageEditorElement;
}
export interface ScreenshotEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLScreenshotEditorElement;
}
declare global {
    interface HTMLImageEditorElementEventMap {
        "editorOutput": { blob: Blob; base64: string };
        "editorClosed": void;
    }
    interface HTMLImageEditorElement extends Components.ImageEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLImageEditorElementEventMap>(type: K, listener: (this: HTMLImageEditorElement, ev: ImageEditorCustomEvent<HTMLImageEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLImageEditorElementEventMap>(type: K, listener: (this: HTMLImageEditorElement, ev: ImageEditorCustomEvent<HTMLImageEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLImageEditorElement: {
        prototype: HTMLImageEditorElement;
        new (): HTMLImageEditorElement;
    };
    interface HTMLScreenshotEditorElementEventMap {
        "screenshotSelected": Blob;
        "editorOpened": void;
        "editorOutput": { blob: Blob; base64: string };
        "editorClosed": void;
    }
    interface HTMLScreenshotEditorElement extends Components.ScreenshotEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLScreenshotEditorElementEventMap>(type: K, listener: (this: HTMLScreenshotEditorElement, ev: ScreenshotEditorCustomEvent<HTMLScreenshotEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLScreenshotEditorElementEventMap>(type: K, listener: (this: HTMLScreenshotEditorElement, ev: ScreenshotEditorCustomEvent<HTMLScreenshotEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLScreenshotEditorElement: {
        prototype: HTMLScreenshotEditorElement;
        new (): HTMLScreenshotEditorElement;
    };
    interface HTMLElementTagNameMap {
        "image-editor": HTMLImageEditorElement;
        "screenshot-editor": HTMLScreenshotEditorElement;
    }
}
declare namespace LocalJSX {
    interface ImageEditor {
        "onEditorClosed"?: (event: ImageEditorCustomEvent<void>) => void;
        "onEditorOutput"?: (event: ImageEditorCustomEvent<{ blob: Blob; base64: string }>) => void;
    }
    interface ScreenshotEditor {
        /**
          * @default 'Take Screenshot'
         */
        "buttonLabel"?: string;
        /**
          * @default 'bottom-right'
         */
        "buttonPosition"?: string;
        "onEditorClosed"?: (event: ScreenshotEditorCustomEvent<void>) => void;
        "onEditorOpened"?: (event: ScreenshotEditorCustomEvent<void>) => void;
        "onEditorOutput"?: (event: ScreenshotEditorCustomEvent<{ blob: Blob; base64: string }>) => void;
        "onScreenshotSelected"?: (event: ScreenshotEditorCustomEvent<Blob>) => void;
        /**
          * @default true
         */
        "showButton"?: boolean;
    }
    interface IntrinsicElements {
        "image-editor": ImageEditor;
        "screenshot-editor": ScreenshotEditor;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "image-editor": LocalJSX.ImageEditor & JSXBase.HTMLAttributes<HTMLImageEditorElement>;
            "screenshot-editor": LocalJSX.ScreenshotEditor & JSXBase.HTMLAttributes<HTMLScreenshotEditorElement>;
        }
    }
}
